version: '3.3'
services:
  clasehtml:
    build: Dockerfiles/php-apache/
    container_name: html-telistema
    # restart: always
    ports:
      - "${PHP_TELISTEMA_PORT}:80"
    env_file: .env
    volumes:
      - "./www/:/var/www/html"
    